# # Generated by Django 5.2.5 on 2025-08-26 11:55

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('iot_api', '0016_remove_devicealarmlog_status_and_more'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='devicealarmlog',
#             name='STATUS',
#             field=models.CharField(default='OPEN', max_length=20),
#         ),
#         migrations.AlterField(
#             model_name='devicealarmlog',
#             name='NORMALIZED_DATE',
#             field=models.DateTimeField(blank=True, null=True),
#         ),
#         migrations.AlterField(
#             model_name='devicealarmlog',
#             name='NORMALIZED_TIME',
#             field=models.DateTimeField(blank=True, null=True),
#         ),
#     ]


from django.db import migrations
import datetime

def convert_normalized_time(apps, schema_editor):
    DeviceAlarmLog = apps.get_model('iot_api', 'DeviceAlarmLog')
    for alarm in DeviceAlarmLog.objects.all():
        if isinstance(alarm.NORMALIZED_TIME, int):
            hours = alarm.NORMALIZED_TIME // 100
            minutes = alarm.NORMALIZED_TIME % 100
            alarm.NORMALIZED_TIME = datetime.time(hour=hours, minute=minutes)
            alarm.save(update_fields=['NORMALIZED_TIME'])
        
        if isinstance(alarm.ALARM_TIME, int):
            hours = alarm.ALARM_TIME // 100
            minutes = alarm.ALARM_TIME % 100
            alarm.ALARM_TIME = datetime.time(hour=hours, minute=minutes)
            alarm.save(update_fields=['ALARM_TIME'])

class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0016_remove_devicealarmlog_status_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_normalized_time),
    ]
